<a href="https://colab.research.google.com/github/fionaliz/Linear_Algebra_ChE_2nd-Sem-2021-2022/blob/main/Assignment_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Linear Algebra for ChE 

Laboratory 6: Matrix operations 

#### Discussion 
In this activity, the students will be able to acquire the follow:
1. Familiarize yourself with basic matrix operations.
2. To solve intermediate equations, use the operations.
3. In engineering problems, use matrix algebra.

In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

### Transposition 

Transposition is a fundamental operation in matrix algebra. The values of a matrix's elements are flipped over its diagonals to transpose it. The rows and columns of the original matrix will be switched as a result of this. As a result, the transpose of a matrix $C$ is denoted by $C^T$. This may now be done programmatically with `np.transpose()` or the `T` function. For instance:

$$C = \begin{bmatrix} 3 & 5 & 4\\7 & -6 &0 \\ 0 & -8 & 8\end{bmatrix} $$

$$ C^T = \begin{bmatrix} 3 & 7 & 0\\5 & -6 &-8 \\ 4 & 0 & 8\end{bmatrix}$$

This can now be achieved programmatically by using `np.transpose()` or using the `T` method.

In [3]:
C = np.array([
    [3 ,5, 4],
    [7, -6, 0],
    [0, -8, 8]
])
C

array([[ 3,  5,  4],
       [ 7, -6,  0],
       [ 0, -8,  8]])

In [4]:
CT1 = np.transpose(C)
CT1

array([[ 3,  7,  0],
       [ 5, -6, -8],
       [ 4,  0,  8]])

In [5]:
CT2 = C.T
CT2

array([[ 3,  7,  0],
       [ 5, -6, -8],
       [ 4,  0,  8]])

In [6]:
np.array_equiv(CT1, CT2)

True

In [7]:
B = np.array([
    [9,1,-9],
    [5,-8,5],
])
B.shape

(2, 3)

In [8]:
np.transpose(B).shape

(3, 2)

In [9]:
B.T.shape

(3, 2)

###Dot Product 

If you remember the dot product from the laboratory activity, we'll try to do the same thing with matrices. We'll retrieve the sum of products of the vectors by row-column pairings in matrix dot product. So, if we have two matrices, $X$ and $Y$, we can deduce:

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:
$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$

$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 & 1*0 + 2*2 \\  0*-1 + 1*2 & 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 & 4 \\2 & 2 \end{bmatrix}$$
This could be achieved programmatically using `np.dot()`, `np.matmul()` or the `@` operator.

In [10]:
X = np.array([
    [3,6],
    [0,4]
])
Y = np.array([
    [-7,8],
    [2,9]
])

In [11]:
np.array_equiv(X, Y)

False

In [12]:
np.dot(X,Y)

array([[-9, 78],
       [ 8, 36]])

In [13]:
X.dot(Y)

array([[-9, 78],
       [ 8, 36]])

In [14]:
X @ Y

array([[-9, 78],
       [ 8, 36]])

In [15]:
np.matmul(X,Y)

array([[-9, 78],
       [ 8, 36]])

In comparison to vector dot products, matrix dot products have additional rules. There are fewer limits because vector dot products are only one dimensional. Since we're dealing with Rank 2 vectors, there are a few rules to keep in mind:

### Rule 1: The inner dimensions of the two matrices in question must be the same. 

Assume you have a matrix A with the shape $(a,b)$, where $a$ and $b$ are any integers. Matrix $B$ should have the shape $(b,c)$, where $b$ and $c$ are any integers, if we want to do a dot product between A and another matrix $B$. As a result, for the following matrices:

$$A = \begin{bmatrix}2&4\\5&-2\\0&1\end{bmatrix}, B = \begin{bmatrix}1&1\\3&3\\-1&-2\end{bmatrix}, C = \begin{bmatrix}0&1&1\\1&1&2\end{bmatrix}$$

So in this case $A$ has a shape of $(3,2)$, $B$ has a shape of $(3,2)$ and $C$ has a shape of $(2,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.  

In [16]:
A = np.array([
    [5, 7, 6],
    [9, -8, 9],
    [0, 3, 6]
])
B = np.array([
    [6,8,9],
    [7,7,7],
    [-8,-4,-5]
])
C = np.array([
    [0,2,2],
    [3,3,4],
    [1,1,1]
])
print(A.shape)
print(B.shape)
print(C.shape)

(3, 3)
(3, 3)
(3, 3)


In [17]:
A @ C

array([[ 27,  37,  44],
       [-15,   3,  -5],
       [ 15,  15,  18]])

In [18]:
B @ C

array([[ 33,  45,  53],
       [ 28,  42,  49],
       [-17, -33, -37]])

If you would notice the shape of the dot product changed and its shape is not the same as any of the matrices we used. The shape of a dot product is actually derived from the shapes of the matrices used. So recall matrix $A$ with a shape of $(a,b)$ and matrix $B$ with a shape of $(b,c)$, $A \cdot B$ should have a shape $(a,c)$.

In [19]:
A @ B.T

array([[140, 126, -98],
       [ 71,  70, -85],
       [ 78,  63, -42]])

In [20]:
X = np.array([
    [4,5,6,7]
])
Y = np.array([
    [8,9,8,-7]
])
print(X.shape)
print(Y.shape)

(1, 4)
(1, 4)


In [21]:
Y.T @ X

array([[ 32,  40,  48,  56],
       [ 36,  45,  54,  63],
       [ 32,  40,  48,  56],
       [-28, -35, -42, -49]])

As it shown that when you try to multiply A and B, it returns `ValueError` pertaining to matrix shape mismatch.

### Rule2
Dot products are common in matrix algebra, which means they have various distinct qualities that should be taken into account while formulating solutions:
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

In [22]:
A = np.array([
    [5,6,7],
    [1,6,8],
    [2,1,0]
])
B = np.array([
    [5,2,7],
    [1,1,1],
    [4,3,3]
])
C = np.array([
    [2,2,0],
    [0,3,3],
    [4,0,4]
])

In [23]:
A.dot(np.zeros(A.shape))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
z_mat = np.zeros(A.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.array_equal(a_dot_z,z_mat)

True

In [27]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

###Determinant

A determinant is a scalar value that can be calculated using a square matrix. In matrix algebra, the determinant is a fundamental and crucial value. Although it will not be clear how it may be utilized realistically in this laboratory, it will be extensively employed in future lessons. 

The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:
$$A = \begin{bmatrix}a_{(0,0)}&a_{(0,1)}\\a_{(1,0)}&a_{(1,1)}\end{bmatrix}$$
We can compute for the determinant as:
$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$
So if we have $A$ as:
$$A = \begin{bmatrix}1&4\\0&3\end{bmatrix}, |A| = 3$$

But what about square matrices that aren't in the shape (2,2)? Several strategies, such as co-factor expansion and the minors method, can be used to solve this problem. This can be taught in a laboratory lecture, but we can use Python to perform the difficult computation of high-dimensional matrices programmatically. Using `np.linalg.det()`, we can accomplish this.

In [28]:
A = np.array([
    [5,7],
    [4,9]
])
np.linalg.det(A)

16.999999999999993

In [29]:
B = np.array([
    [5,7,8],
    [4,9,10],
    [0,3,4]
])
np.linalg.det(B)

13.999999999999991

In [ ]:
## Now other mathematics classes would require you to solve this by hand, 
## and that is great for practicing your memorization and coordination skills 
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.
B = np.array([
    [1,3,5,6],
    [0,3,1,3],
    [3,1,8,2],
    [5,2,6,8]
])
np.linalg.det(B)

-235.0000000000002

### Inverse

Another essential operation in matrix algebra is the inverse of a matrix. We can identify a matrix's solvability and characteristic as a system of linear equations by determining its inverse — we'll go over this more in the nect module. The inverse matrix can also be used to solve the problem of divisibility amongst matrices. Although element-by-element division is possible, dividing matrices as a whole is not. Inverse matrices allow a similar process that might be thought of as "splitting" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:
$$M = \begin{bmatrix}1&7\\-3&5\end{bmatrix}$$
First, we need to get the determinant of $M$.
$$|M| = (1)(5)-(-3)(7) = 26$$
Next, we need to reform the matrix into the inverse form:
$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} & m_{(0,0)}\end{bmatrix}$$
So that will be:
$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 & -7 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} & \frac{-7}{26} \\ \frac{3}{26} & \frac{1}{26}\end{bmatrix}$$
For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use `np.linalg.inv()`.

In [30]:
M = np.array([
    [3,8],
    [-5, 9]
])

np.array(M @ np.linalg.inv(M), dtype=int)

array([[1, 0],
       [0, 1]])

In [31]:
R = np.array([
              [1, 3, 5],
              [7, 9, 2],
              [-4, 6, 8]
])
T = np.linalg.inv(R)
T

array([[ 0.23255814,  0.02325581, -0.15116279],
       [-0.24806202,  0.10852713,  0.12790698],
       [ 0.30232558, -0.06976744, -0.04651163]])

In [32]:
R @ T

array([[ 1.00000000e+00,  1.38777878e-17, -3.46944695e-17],
       [ 1.11022302e-16,  1.00000000e+00, -6.93889390e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [33]:
N = np.array([
    [1,2,2,3,4,4,5],
    [5,6,6,7,8,8,9],
    [0,1,1,2,3,3,4],
    [10,11,11,10,9,9,11],
    [9,8,8,9,7,7,8],
    [-1,13,13,0,0,1,-1],
    [5,3,0,4,5,15,12],
])
N_inv = np.linalg.inv(N)
np.array(N @ N_inv,dtype=int)

array([[  2,   0,   0,   0,   0,   0,   0],
       [  4,  -2,   8,   0,   0,   0,   0],
       [  0,   0,  -1,   0,   0,   0,   0],
       [ -4,  -1,  10,   1,   0,   0,   0],
       [  4,  -1,  20,   0,   1,   0,   0],
       [ 13,  -8,  -8,   0,   0,   0,   0],
       [-15,   4,  21,   0,   0,   0,   1]])

To validate the wether if the matric that you have solved is really the inverse, we follow this dot product property for a matrix $M$:
$$M\cdot M^{-1} = I$$

In [34]:
squad = np.array([
    [1.0, 1.0, 0.5],
    [0.7, 0.7, 0.9],
    [0.3, 0.3, 1.0]
])
weights = np.array([
    [0.2, 0.2, 0.6]
])
p_grade = squad @ weights.T
p_grade


array([[0.7 ],
       [0.82],
       [0.72]])

### Task 1


Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$.
In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 


In [35]:
D = np.array([
    [8, 4, 24],
    [8, 6, -5],
    [9, 1, 15]          
])

O = np.array([
    [17, 35, 79],
    [6, 51, 5],
    [38, -1, -6]          
])

G = np.array([
    [23, 70, -34],
    [24, -9, 8],
    [34, 2, 46]          
])

Property no.1: $A \cdot B \neq B \cdot A$

In [36]:
W= D @ O
W

array([[1072,  460,  508],
       [ -18,  591,  692],
       [ 729,  351,  626]])

In [37]:
E = O @ D
E

array([[1127,  357, 1418],
       [ 501,  335,  -36],
       [ 242,  140,  827]])

In [38]:
np.array_equiv(W, E)

False

Property no.2: $A \cdot (B \cdot C) = (A \cdot B) \cdot C$

In [39]:
M = D @ (O @ G)
M

array([[52968, 71916, -9400],
       [37298, -5195, 37172],
       [46475, 49123,  6818]])

In [40]:
Y = (D @ O) @ G
Y 

array([[52968, 71916, -9400],
       [37298, -5195, 37172],
       [46475, 49123,  6818]])

In [41]:
 np.array_equiv(M, Y)

True

Property no.3: $A\cdot(B+C) = A\cdot B + A\cdot C$

In [42]:
I = D @ (O + G)
I

array([[2168, 1032, 1372],
       [ 140, 1087,  238],
       [1470, 1002, 1018]])

In [43]:
S = D @ O + D @ G
S

array([[2168, 1032, 1372],
       [ 140, 1087,  238],
       [1470, 1002, 1018]])

In [44]:
np.array_equiv(I, S)

True

Propery no.4: $(B+C)\cdot A = B\cdot A + C\cdot A$

In [45]:
L = (O + G) @ D
L

array([[1565,  835, 1110],
       [ 693,  385,  705],
       [ 944,  334, 2323]])

In [46]:
U = O @ D + G @ D
U

array([[1565,  835, 1110],
       [ 693,  385,  705],
       [ 944,  334, 2323]])

In [47]:
np.array_equiv(L, U)

True

Property no.5: $A\cdot I = A$

In [48]:
D@np.eye(3)

array([[ 8.,  4., 24.],
       [ 8.,  6., -5.],
       [ 9.,  1., 15.]])

In [49]:
np.array_equiv(D, D@np.eye(3))

True

Property no.6:  $A\cdot \emptyset = \emptyset$ 

In [60]:
D@np.zeros ((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [61]:
np.array_equiv(D@np.zeros((3,3)), np.zeros((3,3)))

True

In [62]:
D.dot(np.zeros(D.shape))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [63]:
z_mat = np.zeros (D.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [64]:
i_dot_z = D.dot(np.zeros(D.shape))
i_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [65]:
np.array_equal(i_dot_z,z_mat)

True