<a href="https://colab.research.google.com/github/fionaliz/Linear_Algebra_ChE_2nd-Sem-2021-2022/blob/main/Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra fo ChE 
## Assignment 3 : Matrices 
 

Objectives 


## Objectives
At the end of this laboratory activity,the students will be able to:
1. Familiarize the properties of matrix and apply it in writing and working with linear equations.
2. Perform basic matrix operations and classify matrices according to shape and element values.
3. Represent equations in matrices using the Python programming.


# Discussion 

In [15]:
import numpy as np 
import matplotlib.pyplot as plt 
import scipy.linalg as la 
%matplotlib inline 


# Matrices 

Matrices is a rectangular collection of elements or array, arranged in rows and columns. The horizontal and vertical line entries in a matrix are called as rows and columns, represented by *m* and *n* in an *m* *x* *n* matrix.

Let's say we have the equation ***A***, ***B***, and ***C*** 

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        8x - 14y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        8x -14y -z \\
        -x + 8y +14z
    \end{array}
\right. \\
C= \left\{
    \begin{array}
         1w - 1x + 14y -35z \\ 
         3w + 8x - 11y + z \\
         2w - 8x + 2y -2z
    \end{array}
\right. \\
$$


*A* is a system of 2 equations with 2 parameters. While *B* is a system of 3 equations with 3 parameters and *C* is a system of 4 equations with 4 parameters. We can represent them in matrices as:


$$
A=\begin{bmatrix} 1 & 1 \\ 8 & {-14}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 8 & -14 & -1 \\ -1 & 8 & 14\end{bmatrix}\\
C=\begin{bmatrix} 1 & -1 & 14 & -35 \\ 3 & 8 & -11 & 1 \\ 2 & -8 & 2 & -2 \end{bmatrix}\\
$$

## Declaring Matrices 

The numbers in matrices are called the elements of a matrix, arranged in rows and columns that form the array-like structure. These elements are indexed according to their position with respect to their rows and columns. From the equation below, *A* is a matrix consisting of elements denoted as *ai*,*j*. The *i* is the number of rows in the matrix while *j* is the number of columns.
 


$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


In [16]:
## Since we'll keep on describing matrices. let's make a function. 
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [17]:
## Declaring a 2 x 2 matrix 
A = np.array([
     [8, 7],
     [6, 8]        
])
describe_mat(A)

Matrix:
[[8 7]
 [6 8]]

Shape:	(2, 2)
Rank:	2



In [18]:
G = np.array([
    [8,8,6],
    [4,4,7]
])
describe_mat(G)


Matrix:
[[8 8 6]
 [4 4 7]]

Shape:	(2, 3)
Rank:	2



In [19]:
## Declaring a 3 x 2 matrix
B = np.array([
    [9, 2],
    [6, 5],
    [4, 4]
])
describe_mat(B)


Matrix:
[[9 2]
 [6 5]
 [4 4]]

Shape:	(3, 2)
Rank:	2



In [20]:
H = np.array([16,17,18,19])
describe_mat(H)


Matrix:
[16 17 18 19]

Shape:	(4,)
Rank:	1



# Categorizing Matrices  

Classifying matrices could be according to their shape and another is according to their element values.

## According to shape 

### Row and Column Matrices

A row vector (or, row matrix) is a 1-by-*n* matrix. While a column vector (or, column matrix) is a *n*-by-1 matrix. 

In [21]:
## Declaring a Row Matrix

row_mat_1D = np.array([
    4, 5, 6, -7
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [4,5,6,-7]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)

Matrix:
[ 4  5  6 -7]

Shape:	(4,)
Rank:	1

Matrix:
[[ 4  5  6 -7]]

Shape:	(1, 4)
Rank:	2



In [22]:
## declaring of column matrix 
col_mat = np.array([
    [11],
    [22],
    [55]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat)


Matrix:
[[11]
 [22]
 [55]]

Shape:	(3, 1)
Rank:	2



### Square Matrix

Square matrix is a matrix that has equal numbers of row and column sizes. 

In [23]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')


In [24]:
square_mat = np.array([
    [4,8,9],
    [6,6,7],
    [6,1,2]
])

non_square_mat = np.array([
    [4,8,9],
    [6,6,7]
])
describe_mat(square_mat)
describe_mat(non_square_mat)


Matrix:
[[4 8 9]
 [6 6 7]
 [6 1 2]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[4 8 9]
 [6 6 7]]

Shape:	(2, 3)
Rank:	2
Is Square: False



## Accrding to element values

## Null Matrix

Null Matrix is a matrix that has no elements.

In [25]:
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')


In [26]:
null_mat = np.array([])
describe_mat(null_mat)


Matrix is Null


## Zero Matrix

Zero matrix is a matrix whose all elements is zero.

In [27]:
zero_mat_row = np.zeros((4,5))
zero_mat_sqr = np.zeros((5,5))
zero_mat_rct = np.zeros((6,5))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')


Zero Row Matrix: 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Zero Square Matrix: 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Zero Rectangular Matrix: 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## Ones Matrix

Ones matrix is a matrix whose all elements is one.

In [28]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')


Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


## Diagonal Matrix

Diagonal Matrix is a square matrix whose all elements is zero except for those in the diagonal. 

In [29]:
np.array([
    [4,1,1],
    [1,6,1],
    [1,1,8]
])
# a[1,1], a[2,2], a[3,3], ... a[n-1,n-1]

array([[4, 1, 1],
       [1, 6, 1],
       [1, 1, 8]])

In [30]:
d = np.diag([22,33,55,77])
np.diag(d).shape == d.shape[0] == d.shape[1]

False

## Identity Matrix

Identity matrix is a diagonal matrix in which the values at the diagonal are one.

In [31]:
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
np.identity(10)


array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## Upper triangular Matrix

Upper Triangular Matrix has a values of zero below the diagonal of the matrix.

In [33]:
np.array([
    [1,2,3,4],
    [0,3,1,-1],
    [0,0,5,2],
    [0,0,0,2]
])


array([[ 1,  2,  3,  4],
       [ 0,  3,  1, -1],
       [ 0,  0,  5,  2],
       [ 0,  0,  0,  2]])

In [34]:
F = np.array([
              [4,-7,8,-9,10],
              [4,-7,8,-9,10],
              [4,-7,8,-9,10],
              [4,-7,8,-9,10],
              [4,-7,8,-9,10],
])
np.triu(F)

array([[ 4, -7,  8, -9, 10],
       [ 0, -7,  8, -9, 10],
       [ 0,  0,  8, -9, 10],
       [ 0,  0,  0, -9, 10],
       [ 0,  0,  0,  0, 10]])

## Lower Traingular Matrix 


Lower Triangular Matrix has a values of zero above the diagonal of the matrix.

In [35]:
np.array([
    [4,1,1],
    [6,4,1],
    [8,9,3]
])

array([[4, 1, 1],
       [6, 4, 1],
       [8, 9, 3]])

In [36]:
np.tril(F)

array([[ 4,  0,  0,  0,  0],
       [ 4, -7,  0,  0,  0],
       [ 4, -7,  8,  0,  0],
       [ 4, -7,  8, -9,  0],
       [ 4, -7,  8, -9, 10]])

## Matrix Algebra 

### Addition 

In [37]:
A = np.array([
    [8,4],
    [6,7],
    [5,6]
])
B = np.array([
    [8,8],
    [1,1],
    [6,6]
])
A+B

array([[16, 12],
       [ 7,  8],
       [11, 12]])

In [38]:
4+A

array([[12,  8],
       [10, 11],
       [ 9, 10]])

### Subtraction 

In [39]:
A-B

array([[ 0, -4],
       [ 5,  6],
       [-1,  0]])

In [40]:
5-B

array([[-3, -3],
       [ 4,  4],
       [-1, -1]])

### Element-wise Multiplication 

In [41]:
A*B
np.multiply(A,B)

array([[64, 32],
       [ 6,  7],
       [30, 36]])

In [42]:
2*A

array([[16,  8],
       [12, 14],
       [10, 12]])

In [43]:
alpha=10**-10
A/(alpha+B)

array([[1.        , 0.5       ],
       [6.        , 7.        ],
       [0.83333333, 1.        ]])

In [44]:
M = np.array([
    [8,4],
    [6,7],
    [5,6]
])
N = np.array([
    [8,8,5],
    [1,1,6],
])
M@N

array([[68, 68, 64],
       [55, 55, 72],
       [46, 46, 61]])

In [45]:
np.add(A,B)

array([[16, 12],
       [ 7,  8],
       [11, 12]])

**Practice**

1. Given the linear combination below, try to create a corresponding matrix representing it.

$$\theta = 5x + 3y - z$$


In [55]:
num_1 = np.array([
    [5,3,-1],
])
print (num_1)

[[ 5  3 -1]]


2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.

$$
A = \left\{\begin{array}
5w_1 + 4w_2 +7w_3\\
6w_2 - 8w_3\\
12w_3
\end{array}\right.
$$

In [60]:
num_2 = np.array([
    [1,4,7],
    [0,6,-8],
    [0,0,0]
])
describe_mat(num_2)

Matrix:
[[ 1  4  7]
 [ 0  6 -8]
 [ 0  0  0]]

Shape:	(3, 3)
Rank:	2
Is Square: True



3. Given the matrix below, express it as a linear combination in a markdown.

In [57]:
G = np.array ([
    [4,6,8],
    [5,5,5],
    [5,7,9]
])

Answer

Linear combination
$$
G = \left\{
    \begin{array}\
      4x_1+6x_2+8x_3 \\
      5x_1+5x_2-5y_3 \\
      5x_1 + 6x_2 +8x_3
    \end{array}
\right.
$$

LaTex
$$
G=\begin{bmatrix} 4 & 6 & 8 \\ 5 & 5 & 5 \\ 5 & 7 & 9\end{bmatrix}\\
$$

4. Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.

In [59]:
H = np.tril(G)
H


array([[4, 0, 0],
       [5, 5, 0],
       [5, 7, 9]])

Answer

Linear combination
$$
H = \left\{
    \begin{array}\
      4x_1\\
      5x_1+5x_2\\
      5x_1 + 7x_2 +9x_3
    \end{array}
\right.
$$

LaTex
$$
G=\begin{bmatrix} 4 & 0 & 0 \\ 5 & 5 & 0 \\ 5 & 7 & 9\end{bmatrix}\\
$$

# Activity 

##Task 1

Create a function named `mat_desc()` that througouhly describes a matrix, it should: <br>
1. Displays the shape, size, and rank of the matrix. <br>
2. Displays whether the matrix is square or non-square. <br>
3. Displays whether the matrix is an empty matrix. <br>
4. Displays if the matrix is an identity, ones, or zeros matrix <br>
   
Use 5 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [48]:
# mat_desc function

def mat_desc(matrix):
  sq = False
  matrix = np.array(matrix)
  print(matrix)
  print('Shape', matrix.shape)
  print('Size', matrix.size)
  print('Rank', np.linalg.matrix_rank(matrix))
  if(matrix.shape[0] == matrix.shape[1]):
    sq = True
    print('Square Matrix')
  else: 
    print('Non-Square Matrix')
  if(matrix.shape[0] == 0 and matrix.shape[1] == 0):
    print('Empty Matrix')
  else:
    print('Matrix in not Empty')
  identity = np.identity(matrix.shape[0])
  if(sq and (identity == matrix).all()):
    print('Identity Matrix')
  else:
    print('Not an identity matrix')
  ones = np.ones((matrix.shape[0], matrix.shape[1]))
  if(ones == matrix).all ():
    print('Ones matrix')
  else:
    print('Not a Ones Matrix')
  zero = np.zeros((matrix.shape[0], matrix.shape[1]))
  if((zero == matrix).all()):
    print('Zero Matrix')
  else:
    print('Non-Zero Matrix')

In [50]:
print('Example 1: Matrix A')
mat_desc([
    [5,1,0],
    [1,0,-3],
    [4,1,0],
    [-2,9,1]
]) 
print("\t")
print('Example 2: Matrix B')
mat_desc([
    [0,0,0,0],
    [0,0,0,0],
    [0,0,0,0]
])
print("\t")
print('Example 3: Matrix C')
mat_desc([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])
print("\t")
print('Matrix 4: Matrix D')
mat_desc([
    [1,0,0,0],
    [0,1,0,0],
    [0,0,1,0],
    [0,0,0,1]
])
print("\t")
print('Example 5: Matrix E')
mat_desc([
    [1,2,3,0,-6],
    [0,4,-1,5,-11],
    [-3,1,2,0,-5],
    [10,0,3,6,1]
])

Example 1: Matrix A
[[ 5  1  0]
 [ 1  0 -3]
 [ 4  1  0]
 [-2  9  1]]
Shape (4, 3)
Size 12
Rank 3
Non-Square Matrix
Matrix in not Empty
Not an identity matrix
Not a Ones Matrix
Non-Zero Matrix
	
Example 2: Matrix B
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Shape (3, 4)
Size 12
Rank 0
Non-Square Matrix
Matrix in not Empty
Not an identity matrix
Not a Ones Matrix
Zero Matrix
	
Example 3: Matrix C
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
Shape (3, 4)
Size 12
Rank 1
Non-Square Matrix
Matrix in not Empty
Not an identity matrix
Ones matrix
Non-Zero Matrix
	
Matrix 4: Matrix D
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
Shape (4, 4)
Size 16
Rank 4
Square Matrix
Matrix in not Empty
Identity Matrix
Not a Ones Matrix
Non-Zero Matrix
	
Example 5: Matrix E
[[  1   2   3   0  -6]
 [  0   4  -1   5 -11]
 [ -3   1   2   0  -5]
 [ 10   0   3   6   1]]
Shape (4, 5)
Size 20
Rank 4
Non-Square Matrix
Matrix in not Empty
Not an identity matrix
Not a Ones Matrix
Non-Zero Matrix


## Task 2

Create a function named Create a function named `mat_operations()` that takes in two matrices a input parameters it should:<br>

1. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
2. Returns the sum of the matrices.
3. Returns the differen of the matrices.
4. Returns the element-wise multiplication of the matrices.
5. Returns the element-wise division of the matrices.


Use 5 sample matrices in which their shapes are not lower than  $(3,3)$ . In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.



In [53]:
#mat_operations function
MatrixA 
def mat_operations(matrixA, matrixB):
    matrixA = np.array(matrixA)
    matrixB = np.array(matrixB)
    print('Matrix A:', matrixA)
    print('Matrix B:', matrixB)
    if(matrixA.shape != matrixB.shape):
        print('The dimensions of the two matrices are not equal. Operation Error.')
        return
    print('Sum Matrix A and Matrix B:')
    matrixsum = matrixA + matrixB
    print(matrixsum)
    print('Difference of Matrix A and Matrix B:')
    matrixdiff = matrixA - matrixB
    print(matrixdiff)
    print('Element-wise multiplication of Matrix A and Matrix B:')
    matrixmulti = np.multiply(matrixA, matrixB)
    print(matrixmulti)
    print('Element-wise division of Matrix A and Matrix B:')
    matrixdiv = np.divide(matrixA, matrixB)
    print(matrixdiv)

In [54]:
print('Example 1:')
MatrixA = np.array([
              [4,6,8],
              [5,5,5],
              [5,7,9]
])
MatrixB = np.array([
              [-1,2,-3],
              [4,5,6],
              [-7,-8,9]
])
mat_operations(MatrixA,MatrixB)
print("\t") 
print('Example 2:')
MatrixA = np.array ([
             [5,1,12,11],
             [-1,-2,3,5],
             [5,7,9,7],
             [8,1,13,-4]
])
MatrixB = np.array([
              [-1,5,2,-3],
              [4,10,5,6],
              [-7,13,-8,9],
              [17,-17,5,3]
])
mat_operations(MatrixA,MatrixB)
print("\t") 
print('Example 3:')
MatrixA = np.array ([
             [3,1,12,11,5],
             [-1,2,3,3,1],
             [5,7,9,10,-1],
])
MatrixB = np.array([
              [1,9,2,3,1],
              [4,-10,-5,6,1],
              [7,13,8,9,1],
])
mat_operations(MatrixA,MatrixB)
print("\t") 
print('Example 4:')
MatrixA = np.array ([
             [8,1,12,11,5],
             [-1,2,4,7,1],
             [5,7,9,10,-1],
             [3,19,-13,11,1]
])
MatrixB = np.array([
              [1,8,2,3,1],
              [4,-10,-5,6,1],
              [7,13,8,9,1],
              [-1,13,2,3,1]
])
mat_operations(MatrixA,MatrixB)
print("\t") 
print('Example 5:')
MatrixA = np.array ([
             [1,1,12,11,2,4],
             [-1,2,2,-4,1,3],
             [5,7,9,10,-1,2],
])
MatrixB = np.array([
              [1,12,2,3,1,4],
              [4,-10,-5,6,1,3],
              [7,13,8,9,1,2],
])
mat_operations(MatrixA,MatrixB)

Example 1:
Matrix A: [[4 6 8]
 [5 5 5]
 [5 7 9]]
Matrix B: [[-1  2 -3]
 [ 4  5  6]
 [-7 -8  9]]
Sum Matrix A and Matrix B:
[[ 3  8  5]
 [ 9 10 11]
 [-2 -1 18]]
Difference of Matrix A and Matrix B:
[[ 5  4 11]
 [ 1  0 -1]
 [12 15  0]]
Element-wise multiplication of Matrix A and Matrix B:
[[ -4  12 -24]
 [ 20  25  30]
 [-35 -56  81]]
Element-wise division of Matrix A and Matrix B:
[[-4.          3.         -2.66666667]
 [ 1.25        1.          0.83333333]
 [-0.71428571 -0.875       1.        ]]
	
Example 2:
Matrix A: [[ 5  1 12 11]
 [-1 -2  3  5]
 [ 5  7  9  7]
 [ 8  1 13 -4]]
Matrix B: [[ -1   5   2  -3]
 [  4  10   5   6]
 [ -7  13  -8   9]
 [ 17 -17   5   3]]
Sum Matrix A and Matrix B:
[[  4   6  14   8]
 [  3   8   8  11]
 [ -2  20   1  16]
 [ 25 -16  18  -1]]
Difference of Matrix A and Matrix B:
[[  6  -4  10  14]
 [ -5 -12  -2  -1]
 [ 12  -6  17  -2]
 [ -9  18   8  -7]]
Element-wise multiplication of Matrix A and Matrix B:
[[ -5   5  24 -33]
 [ -4 -20  15  30]
 [-35  91 -72  63]
